### ISSUE TITLE
Nginx support

### ISSUE THREAD

**Issue by nicolasbadia** [cavo789/marknotes#20]
Hi,
I just discover your app which seem pretty awesome.
I'm using nginx on my server and it doesn't seem to work properly with it.
By any chance, do you have an nginx configuration I could use?
Otherwise, could you give me some tips to make one?

**Comment by nicolasbadia** [comment]
Actually, I'm not sure the issue is my nginx configuration...
Here it is for the record:


```
server {
  listen 80;
  server_name marknotes.example.com;
  rewrite ^ https://$host$request_uri? permanent;
}

server {
  listen 443 ssl;
  server_name marknotes.example.com;

  root /home/marknotes/src;
  index index.php;

  try_files $uri $uri/ /index.php?$args;

  location ~ \.php$ {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;

    fastcgi_pass unix:/run/php/php-fpm.sock;
    fastcgi_index index.php;
    include fastcgi_params_gx;
  }
}

```

The problem is that when I rename a file and reload the page, a POST request is done to `https://marknotes.gestixi.com/index.php` which return a 404 error:

> Le fichier [/home/marknotes/src/docs/0b535208dde7a6bc329ce6143684dbc4test.md] n'existe pas

And in the browser, the 0b535208dde7a6bc329ce6143684dbc4test.md file is displayed while it as been renamed on the server...

Any idea of what might be the problem?

**Comment by cavo789** [comment]
Hi Nicolas

Thanks for trying marknotes.

The error message is an intern one : not related to nginx.  I've had this problem the last days too on my localhost; since my last tentative to offer support for accentuated characters in filename (it's a real pitty under PHP to manage this, on Unix and on Windows).

I'll take a look on this today.

For nginx : yes, you're right, my .htaccess is designed for Apache.  You'll certainly get troubles with rewrited URLs; yeah, indeed, but not for the main interface. And sorry, I've no experience at all with nginx, never tried to install this on my Windows machine (is there installation packages?)

I'll test and comes back soon... during the day I hope.

**Comment by cavo789** [comment]
After a few tries (on my **Apache** local webserver), I was not able to reproduce this problem. I've find an error with ajax when editing notes with accentuated characters (solved now) but nothing with the rename actions.

I read your message once more and I didn't really understand this sentence : 

`The problem is that when I rename a file and reload the page, a POST request is done to xxx/index.php which return a 404 error:`

I didn't understand why this is a POST and not a GET : the rename action is done by Ajax so "behind" the scene. By refreshing the page, you don't call ajax but your last interactive "browser" action (don't know how to call this ;) ) i.e. the display of the main interface so it's a GET not a POST. I've just try it right now in my browser with the "Preserve log" option checked.

Concerning the display of the note, probably due to the cache.  marknotes use different levels of cache : on server side and on client side.

If you want to disable caching, please create a `settings.json` file in your application root folder and put these lines in it : 

```json
{	
	"plugins": {
		"options": {
			"optimisation": {
				"browser_cache": 0,
				"localStorage": 0,
				"server_session": 0
			}
		}
	}
}
```

If you want to enable debugging, use this instead : 

```json
{	
	"debug": 1,
	"plugins": {
		"options": {
			"optimisation": {
				"browser_cache": 0,
				"localStorage": 0,
				"server_session": 0
			}
		}
	}
}
```

Then, in your application root folder, you'll find the /tmp/debug.log file with a lot of valuable informations.  Note : you can also set "development":1 for deeper debug info.

Have a nice day.

**Comment by nicolasbadia** [comment]
I did a little more testing. To avoid the issue, I had to disable `localStorage` and `server_session`. If I keep one of them on, I get the 404 AJAX request error (which is indeed a GET).


![capture d ecran 2017-07-05 a 07 49 50](https://user-images.githubusercontent.com/477089/27850840-6b706f0e-6157-11e7-9895-b30a7137f93b.png)

![capture d ecran 2017-07-05 a 07 57 23](https://user-images.githubusercontent.com/477089/27850876-98b33b04-6157-11e7-9682-ba1d884253da.png)

**Comment by cavo789** [comment]
Great, we are one step further.

So, to fully understand : 

1. The software main interface is working (you can open it, see the treeview with the list of files, ...)
2. You make a right-clic on the treeview and select "Rename"; this one a note (not a folder)
3. Once you've given the new name, the file is well renamed on disk but the reload of the note gives an error.

Is it correct ?

By disabling the caching features, the result is like expected : once renamed, the note is well displayed.

**Comment by nicolasbadia** [comment]
That's it. And if I enable back the cache the problem come back. The file were renamed yesterday and I keep having the same issue (the cache was not invalidated and is in a wrong state I think).

Also note that if I disable the cache > rename a file > select another > and go back to the renamed file, I get the message "Un peu de patience s'il vous plaît..."  (on peut parler français aussi si tu préfères ;-)). I then need to reload the page to get the content of the file again.

**Comment by cavo789** [comment]
I'll make some more tests... On my dev machine, I've disabling cache features.  *(oui, j'avais vu que tu étais francophone; on peut continuer en anglais pour ceux qui liraient ce post plus tard si c'est OK pour toi)*

**Comment by nicolasbadia** [comment]
Ok thanks. For now, it works pretty well without cache.
Thanks for the quick support by the way.

**Comment by cavo789** [comment]
I've push a newer version that should solve the cache invalidation : https://github.com/cavo789/marknotes/blob/master/src/marknotes/plugins/content/html/treeview/treeview.js#L245-L259

By adding, renaming or removing a folder / file, the localStorage object will be cleared.

**Comment by nicolasbadia** [comment]
Still an issue after the update
