### ISSUE TITLE
Blue screen after update

### ISSUE THREAD

**Issue by micker** [cavo789/marknotes#30]
hello i update marknote with update script now i have only blue screen ...
https://flexicontent.org/documentation_notes/
some idea ?

**Comment by cavo789** [comment]
Hello Yannick

Right now your site is working fine.

Note : since I still have FTP credentials; I've modified yours settings to no more use "/docs" as folder but "/flexi".  Why ? Doing this will make sure that you won't see again the Introduction file of marknotes (put in the /docs folder). 

Have a nice day.

(I'll close this issue but don't hesitate to reopen if needed)

**Comment by micker** [comment]
thanks
